name: MauiRedWeek
favicon: null
layout_spectrum: 0.13811188586987555
typography_spectrum: 0.23413787223398685
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6d6d6'
    - '#452e28'
    - '#b7a692'
    - '#817f73'
    - '#3ba723'
  brandStrength: 0.4174030607100576
  lightness: 0.5865635734517127
  saturation: 0.8477099935989827
  rhythmicContrast: 0.22889754292555153
purpose: []
